
pipeline {
    agent any
    stages {

        stage('Test') {
            steps {
                echo 'Packaging....'
                # sh 'mvn -Dmaven.test.skip=true clean package'
            }
        }
        stage('Integration Test') {
                    steps {
                        echo 'Integration Test....'
                        sh 'pwd  '
                        sh 'cd docker/bin && ls -l '
                        sh './integrate_test.sh'
                    }
                }


    }
    post {
        failure {
          updateGitlabCommitStatus name: 'build', state: 'failed'
        }
        success {
          updateGitlabCommitStatus name: 'build', state: 'success'
        }
        always {
        script {
            def resultIcon = currentBuild.result == 'SUCCESS' ? ':white_check_mark:' : ':anguished:'
            addGitLabMRComment comment: "$resultIcon Jenkins Build $currentBuild.result\n\nResults available at: [Jenkins [$env.JOB_NAME#$env.BUILD_NUMBER]]($env.BUILD_URL)"
            echo 'I will always say Hello again!'
           }
         }
      }

}